using Newtonsoft.Json.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace PyrusApiClient
{
	[JsonConverter(typeof(StringEnumConverter))]
	public enum SourceType
	{
		[EnumMember(Value = "default")] Default = 0,
		[EnumMember(Value = "sales_force")] Salesforce = 1,
		[EnumMember(Value = "amo_crm")] AmoCRM = 2,
		[EnumMember(Value = "quickbooks_gl_codes")] Quickbooks_GlCodes = 3,
		[EnumMember(Value = "quickbooks_vendors")] Quickbooks_Vendors = 4,
		[EnumMember(Value = "hierarchical")] Hierarchical = 5,
		[EnumMember(Value = "unknown_gl_codes")] Unknown_GlCodes = 6,
		[EnumMember(Value = "unknown_vendors")] Unknown_Vendors = 7,
		[EnumMember(Value = "gp_gl_codes")] GP_GlCodes = 8,
		[EnumMember(Value = "gp_vendors")] GP_Vendors = 9,
		[EnumMember(Value = "quickbooks_online_gl_codes")] QuickbooksOnline_GlCodes = 10,
		[EnumMember(Value = "quickbooks_online_vendors")] QuickbooksOnline_Vendors = 11,
		[EnumMember(Value = "department_catalog")] DepartmentCatalog = 12,
		[EnumMember(Value = "sap_gl_codes")] SAP_GlCodes = 13,
		[EnumMember(Value = "sap_vendors")] SAP_Vendors = 14,
		[EnumMember(Value = "unknown_customers")] Unknown_Customers = 15,
		[EnumMember(Value = "quickbooks_customers")] Quickbooks_Customers = 16,
		[EnumMember(Value = "quickbooks_terms")] Quickbooks_Terms = 17,
		[EnumMember(Value = "quickbooks_customer_messages")] Quickbooks_CustomerMessages = 18,
		[EnumMember(Value = "amo_crm_companies")] AmoCRM_Companies = 19,
		[EnumMember(Value = "quickbooks_online_tax_codes")] QuickbooksOnline_TaxCodes = 20,
		[EnumMember(Value = "quickbooks_classes")] Quickbooks_Classes = 21,
		[EnumMember(Value = "quickbooks_sales_tax_codes")] Quickbooks_SalesTaxCodes = 22,
		[EnumMember(Value = "quickbooks_sales_reps")] Quickbooks_SalesReps = 23,
		[EnumMember(Value = "quickbooks_items")] Quickbooks_Items = 24,
		[EnumMember(Value = "one_s_contractors")] OneS_Contractors = 25,
		[EnumMember(Value = "fill_table")] FillTable = 26,
		[EnumMember(Value = "logisuite_vendors")] Logisuite_Vendors = 27,
		[EnumMember(Value = "one_s_organizations")] OneS_Organizations = 28,
		[EnumMember(Value = "sapb1_gl_codes")] SAPB1_GlCodes = 31,
		[EnumMember(Value = "sapb1_vendors")] SAPB1_Vendors = 32,
		[EnumMember(Value = "quickbooks_online_classes")] QuickbooksOnline_Classes = 33,
		[EnumMember(Value = "sapb1_items")] SAPB1_Items = 34,
		[EnumMember(Value = "sapb1_customers")] SAPB1_Customers = 35,
		[EnumMember(Value = "diadoc_organizations")] Diadoc_Organizations = 36,
		[EnumMember(Value = "blackbaud_nxt_accounts")] BlackbaudNxt_Accounts = 37,
		[EnumMember(Value = "blackbaud_nxt_vendors")] BlackbaudNxt_Vendors = 38,
		[EnumMember(Value = "blackbaud_nxt_projects")] BlackbaudNxt_Projects = 39,
		[EnumMember(Value = "blackbaud_nxt_classes")] BlackbaudNxt_Classes = 40,
		[EnumMember(Value = "net_suite_vendors")] NetSuite_Vendors = 41,
		[EnumMember(Value = "net_suite_gl_codes")] NetSuite_GlCodes = 42,
		[EnumMember(Value = "net_suite_items")] NetSuite_Items = 43,
		[EnumMember(Value = "sbis_organizations")] Sbis_Organizations = 44,
		[EnumMember(Value = "net_suite_classes")] NetSuite_Classes = 45,
		[EnumMember(Value = "unknown_projects")] Unknown_Projects = 46,
		[EnumMember(Value = "unknown_classes")] Unknown_Classes = 47,
		[EnumMember(Value = "quickbooks_online_tax_customers")] QuickbooksOnline_Customers = 48,
		[EnumMember(Value = "bamboo_hr_employees")] BambooHr_Employees = 49,
		[EnumMember(Value = "blackbaud_nxt_bank_accounts")] BlackbaudNxt_BankAccounts = 50,
		[EnumMember(Value = "unknown_bank_accounts")] Unknown_BankAccounts = 51,
		[EnumMember(Value = "unknown_tax_codes")] Unknown_TaxCodes = 52,
		[EnumMember(Value = "quickbooks_employees")] Quickbooks_Employees = 53,
		[EnumMember(Value = "quickbooks_payroll_item_wage")] Quickbooks_PayrollItemWage = 54,
		[EnumMember(Value = "quickbooks_item_service")] Quickbooks_ItemService = 55,
		[EnumMember(Value = "sage_intacct_vendors")] SageIntacct_Vendors = 56,
		[EnumMember(Value = "sage_intacct_accounts")] SageIntacct_Accounts = 57,
		[EnumMember(Value = "sage_intacct_departments")] SageIntacct_Departments = 58,
		[EnumMember(Value = "sage_intacct_locations")] SageIntacct_Locations = 59,
		[EnumMember(Value = "sage_intacct_projects")] SageIntacct_Projects = 60,
		[EnumMember(Value = "sage_intacct_tasks")] SageIntacct_Tasks = 61,
		[EnumMember(Value = "sage_intacct_cost_types")] SageIntacct_CostTypes = 62,
		[EnumMember(Value = "quickbooks_online_items")] QuickbooksOnline_Items = 63,
		[EnumMember(Value = "unknown_items")] Unknown_Items = 64,
		[EnumMember(Value = "net_suite_departments")] NetSuite_Departments = 65,
		[EnumMember(Value = "quickbooks_online_terms")] QuickbooksOnline_Terms = 66,
		[EnumMember(Value = "unknown_terms")] Unknown_Terms = 67,
		[EnumMember(Value = "net_suite_employees")] NetSuite_Employees = 68,
		[EnumMember(Value = "net_suite_vendor_addresses")] NetSuite_VendorAddresses = 69,
		[EnumMember(Value = "edi_org_details_ru")] EdiOrgDetailsRU = 70,
		[EnumMember(Value = "sage_intacct_customers")] SageIntacct_Customers = 71,
		[EnumMember(Value = "sage_intacct_items")] SageIntacct_Items = 72,
		[EnumMember(Value = "sage_intacct_classes")] SageIntacct_Classes = 73,
	}
}
